name: hello-world
on: push
jobs:
   my-job:
      runs-on: ubuntu-latest
      steps:
         - name: my-step
           run: echo "hello world"
   my-jolkhb:
      runs-on: ubuntu-latest
      needs: my-job
      steps:
         - name: moh
           run: echo "Hil Mohamed"
         
